In [23]:
import numpy as np
import matplotlib.pyplot as plt
import pickle
from mpl_toolkits.mplot3d import Axes3D


%matplotlib notebook

In [6]:
pkl_file_comp_on = open('data/circle_compensation_on.pkl', 'rb')
vicon_on, state_on, _, _, error_on = pickle.load(pkl_file_comp_on)
pkl_file_comp_on.close()

In [8]:
pkl_file_comp_off = open('data/circle_compensation_off.pkl', 'rb')
vicon_off, state_off, _, _, error_off = pickle.load(pkl_file_comp_off)
pkl_file_comp_off.close()

In [9]:
print(state_on['torque']['right_s1'][:20])

[0.0, -50.0, -50.0, 0.0, 0.0, 0.0, -50.0, -50.0, 0.0, 0.0, 0.0, 0.0, -50.0, -50.0, -50.0, -50.0, -50.0, -50.0, 0.0, 0.0]


In [37]:
err_fig = plt.figure()
err_fig.add_subplot(211)
plt.plot(error_on[100:-100])
plt.ylabel('meters')
plt.title('World frame end effector position error: Compensation on')
plt.legend(['x', 'y', 'z'])
plt.ylim([0, 0.4])
err_fig.add_subplot(212)
plt.plot(error_off[100:-100])
plt.title('World frame end effector position error: Compensation off')
plt.legend(['x', 'y', 'z'])
plt.xlabel('index')
plt.ylabel('meters')
plt.ylim([0, 0.4])

plt.show()

<IPython.core.display.Javascript object>

In [38]:
#plot for desired trajectory vs. executed trajectory without gravity compensation

end_effector_fig = plt.figure()
# end_effector_fig.add_subplot(111)
ax = end_effector_fig.add_subplot(111, projection='3d')
ax.plot(np.array(vicon_on)[100:-100,0], np.array(vicon_on)[100:-100,1], np.array(vicon_on)[100:-100,2], color = 'b')
plt.ylabel('meters')
plt.title('World frame end effector position: Desired vs. Performed', y=1.08)
plt.legend(['x', 'y', 'z'])
# ax = end_effector_fig.add_subplot(212, projection='3d')
ax.plot(np.array(vicon_off)[100:-100,0], np.array(vicon_off)[100:-100,1], np.array(vicon_off)[100:-100,2], color = 'r')
plt.ylabel('meters')
# plt.title('World frame end effector position: Compensation off')
plt.legend(['Executed (with compensation)', 'Executed (no compensation)'], loc=3)
plt.show()

<IPython.core.display.Javascript object>

In [19]:
# print(vicon_on)

vicon_on_np = np.array(vicon_on)

print(vicon_on_np)

[[ 0.15811057 -0.42509883  0.33102359]
 [ 0.15701119 -0.42336404  0.33173218]
 [ 0.1562631  -0.42278935  0.33196455]
 ...
 [ 0.87740053 -0.79236412  0.95156886]
 [ 0.87740053 -0.79236412  0.95156886]
 [ 0.87812512 -0.79087667  0.95084337]]
